### ISSUE TITLE
flatpak installs?

### ISSUE THREAD

**Issue by salverde** [Delppine1024/TGreen#10]
Hey first wanna say thanks much for this! I'll purchase a license later when Im not so nomadic.

But where shall I copy this file? I do not a resources directory in

`$HOME/.var/app/io.typora.Typora/` 
or anywhere under it?

halp?

**Comment by Delppine1024** [comment]
You could use recursive method to check file/folder names under possible installation directory. Maybe you could use `grep` to filter output from previous command. The purpose is to find **`app.asar`**.

**Comment by Delppine1024** [comment]
Basically, we got default path of Typora installation at /usr/shared/typora. You could utilize ''whereis typora' to check location
