### ISSUE TITLE
内网环境补丁失效

### ISSUE THREAD

**Issue by TieZhu-Liu** [Delppine1024/TGreen#12]
### 安装平台
OS 名称:          Microsoft Windows 10 企业版 LTSC
OS 版本:          10.0.17763 暂缺 Build 17763
OS 制造商:        Microsoft Corporation

### 安装方式
软件安装：默认安装方式安装到 C:\Program Files\Typora
破解安装：替换文件C:\Program Files\Typora\resources\app.asar

#### 网络环境
内网环境并有代理
#### 左下角未激活消失，但还是会显示激活页面
![image](https://github.com/user-attachments/assets/dd7e2e51-cee9-4b7b-9312-6bfd08bcf0bd)

**Comment by Delppine1024** [comment]
之前有没有试过其他的激活方式呢？如果有dll文件是需要卸载的

**Comment by TieZhu-Liu** [comment]
> 之前有没有试过其他的激活方式呢？如果有dll文件是需
