### ISSUE TITLE
Support for version 1.5.13

### ISSUE THREAD

**Issue by godiecl** [Delppine1024/TGreen#3]
Hi, currently the Typora had version **1.5.13** and the repository latest version is **1.5.10**. The last version is located here: https://typora.io/releases/all, can you patch de latest version?

**Comment by SnapdragonLee** [comment]
hello, in order to avoid Typora's super fast verification update, I decided to delay new release until the next second version is released, So I will wait until 1.54 or 1.6 to release 1.5.12. Btw, I do have completed 1.5.12 version patches. Please wait, thanks!

**Comment by Delppine1024** [comment]
hello, in order to avoid Typora's super fast verification update, I decided to delay new release until the next second version is released. So I will wait until 1.54 or 1.6 to release 1.5.12. Btw, I do have completed 1.5.12 version patches. Please wait, thanks!

**Comment by bequt** [comment]
1.6.5发布了

**Comment by Delppine1024** [comment]
@bequt 我会发布1.6.4-dev以及之前的所有版本，当1.6.6或更新版本发布时，我会推出1.6.5
