### ISSUE TITLE
1.6.6 windows x64版本补丁貌似失效了

### ISSUE THREAD

**Issue by FKcrown** [Delppine1024/TGreen#4]
替换app.asar之前备份了一下原版的文件，替换后发现软件打不开了。
然后恢复了原版的app.asar文件，发现软件可以打开了，许可证也显示已激活
![image](https://github.com/Delppine1024/TGreen/assets/79238509/102c172c-2847-493b-9540-b1f4082d3d97)
![image](https://github.com/Delppine1024/TGreen/assets/79238509/b0a5b1f1-e0d7-4bb2-96e8-ffb9ccb619b3)
## 但是这个激活并不稳定，等待一段时间后激活许可消失了
![image](https://github.com/Delppine1024/TGreen/assets/79238509/00cb0c39-1be8-4adb-804b-eb79da52f649)
然后我继续尝试使用破解的app.asar替换原版app.asar，发现软件还是打不开

**Comment by Delppine1024** [comment]
请详细提供您的系统平台，安装方式，和其它可提供信息
如果有其他人也遇到了这个问题，可以在这个issue下方留言

**Comment by FKcrown** [comment]
> 请详细提供您的系统平台，安装方式，和其它可提供信息 如果有其他人也遇到了这个问题，可以在这个issue下方留言


# 安装平台
版本	Windows 11 专业工作站版 Insider Preview
版本	22H2
安装日期	‎2023-‎06-‎12
操作系统版本	23475.1000
序列号	PF3A786T
体验	Windows Feature Experience Pack 1000.23475.1000.0

# 安装方式
软件安装：默认安装方式安装到 `C:\Program Files\Typora`
破解安装：替换文件`C:\Program Files\Typora\resources\app.asar`

# 其他可提供信息
今天打开软件依然会先显示【Typora已激活】，再次打开软件许可证信息会显示 【许可证还有0天到期】，情况和上一条comment类似

**Comment by Delppine1024** [comment]
作为作者 我无法复现这个问题，很抱歉，我个人的系统为：
版本 Windows 10 IoT Enterprise LTSC
版本 21H2
安装日期 ‎2023-‎01-21
操作系统版本 19044.3086

**Comment by 87zrjojo** [comment]
会不会是自动更新了造成了，我这边月用着也没问题

**Comment by FKcrown** [comment]
> 会不会是自动更新了造成了，我这边月用着也没问题

没有开过自动更新，你用的是1.6.6版本吗

**Comment by 87zrjojo** [comment]
我在win11中安装的1.6.6用了有一段时间了

**Comment by SnapdragonLee** [comment]
> > 会不会是自动更新了造成了，我这边月用着也没问题
> 
> 
> 
> 没有开过自动更新，你用的是1.6.6版本吗

想到了一点，之前有没有用过winmm.dll，用过那种方式记得删掉那个dll动态链接库，因为1.6.x版会让该动态链接库使用一段时间后激活失效。

有其他原因的话可以再反馈

**Comment by Delppine1024** [comment]
想到了一点，之前有没有用过winmm.dll，用过那种方式记得删掉那个dll动态链接库，因为1.6.x版会让该动态链接库使用一段时间后激活失效。

正常情况下，原本的app.asar肯定不会判定其为激活成功，我个人认为肯定你以前有用过其他的激活方式，具体是什么方式可以自己检查一下，期待您的回复。

当然，如果有其他原因的话也可以再反馈~

**Comment by FKcrown** [comment]
目录里确实有个winmm.dll，但我不记得有修改过这个文件，也不知道这个文件从哪里来的。如果出现这个文件，请问我应该如何操作 
![image](https://github.com/Delppine1024/TGreen/assets/79238509/41d19ec1-831c-4342-ae97-e4c5ef39cd08)

**Comment by Delppine1024** [comment]
这个文件是之前网上流行的通用激活补丁，来源于win程序启动加载动态链接库直接激活。目前这个版本好像不太稳定，您需要删除这个文件，然后按照readme中的替换应该就可以了

**Comment by FKcrown** [comment]
好的，谢谢，我会按照你的说法尝试并及时反馈

**Comment by Delppine1024** [comment]
> 

好的，期待 ~

**Comment by FKcrown** [comment]
我删除了winmm.dll文件，卸载重装了windows1.6.6 x64版本，并按照readme中的说法替换了文件，现在破解成功且不会出现激活许可消失的情况，看来确实是winmm.dll文件的问题

**Comment by Delppine1024** [comment]
OK 好的，如果没有其他问题我会将本问题关闭并置顶

**Comment by smallBG** [comment]
win版1.10.6最新版无法成功

**Comment by SnapdragonLee** [comment]
> win版1.10.6最新版无法成功

我都还没来得及做呢 肯定不行了hh
六日我会抽时间做一下

**Comment by smallBG** [comment]
> > win版本1.10.6最新版本无法成功
> 
> 我还没来得及做呢呢肯定不行了啊 六日我会抽出时间做一下

好的，期待大佬能够完成

**Comment by smallBG** [comment]
> > win版本1.10.6最新版本无法成功
> 
> 我还没来得及做呢呢肯定不行了啊 六日我会抽出时间做一下

怎么样了老哥，好做吗

**Comment by smallBG** [comment]
老哥，不更新了吗

**Comment by Delppine1024** [comment]
> 老哥，不更新了吗

会做 别着急
