### ISSUE TITLE
1.73正式版已出

### ISSUE THREAD

**Issue by wqiucheng** [Delppine1024/TGreen#6]
作者你好，1.73正式版已出，烦请更新，谢谢

**Comment by Delppine1024** [comment]
就像我之前所说的一样，我会延迟这个版本的更新，新版本已经做好了，就差上传。

Tp一直在对可能的patch位置打补丁，做patch这件事越来越难，我不希望Tp侦测到patch这个事的发生，因此我希望延缓Tp对于打补丁字节验证的更新速度，请您谅解。

新版来了一个大的，敬请期待，我会适时上传这个版本的。

*您可以watch这个项目，这样产生新的release时可以及时通知您，谢谢您的理解。

**Comment by Delppine1024** [comment]
有兴趣的话您可以来一些群里面查看相关信息：
QQ群：615170362
Telegram: https://t.me/crazytpr
