### ISSUE TITLE
Mac版本的补丁包

### ISSUE THREAD

**Issue by hczhch** [Delppine1024/TGreen#7]
你好，请问会出Mac版本的补丁包吗？

**Comment by Delppine1024** [comment]
> 你好，请问会出Mac版本的补丁包吗？

目前没有计划，Mac印象里不是用的Electron框架统一分发的，所以暂时不适用。
但是我看网上支持mac版本的一大把，感觉也没有大费周章研究的必要，很抱歉（

**Comment by MTDickens** [comment]
mac 推荐 https://github.com/QiuChenly/InjectLib
