### ISSUE TITLE
为什么不直接更新到1.8.9呢

### ISSUE THREAD

**Issue by 87zrjojo** [Delppine1024/TGreen#9]
最新版不是1.8.9吗？目前测试可以用，但显示的是1.8.8，期待更新

**Comment by Delppine1024** [comment]
因为我不想让补丁文件传播太快，所以我也不允许任何人fork，已经fork的人已经被我block了。
之前我22年发的时候就被封了，难道还想让我被作者投诉一次？而且更新太快作者会更改加密的，给我没有酬劳的兴趣爱好增加了很多没必要的负担，我觉得不好

**Comment by Delppine1024** [comment]
我已经有讲过，会根据最新版延迟一个版本再进行更新，这是惯例

**Comment by Delppine1024** [comment]
如果您有想了解的信息，看我的置顶issue，里面有很多额外信息，谢谢

**Comment by 87zrjojo** [comment]
感谢回复，了解了，希望持续更新。

**Comment by Delppine1024** [comment]
嗯好的，谢谢您的理解
